// client/src/components/vue/LayoutBar.vue
<template>
  <div
    class="w-screen bg-white grid grid-rows-1 grid-cols-[1fr_auto_auto] items-center layout-bar-container shadow-sm" style="height: var(--layout-bar-height);">
    <div style="color: var(--layout-bar-title-color)" class="select-none">
      AnomalousVehicleTrajectoryAlertSystem
    </div>
    <div class="h-full">
      <slot name="tap" />
    </div>
    <div>
      <slot name="user" />
    </div>
  </div>
</template>

<script setup lang="ts" name='LayoutBar'>

</script>

<style scoped lang="scss">
.layout-bar-container {
  padding-right: calc(var(--spacing) * 4);
  padding-left: calc(var(--spacing) * 4);
  background-color: var(--layout-bar-bg);
  color: var(--layout-bar-color);
}
</style>

// client/src/components/Layout/LayoutBar.tsx
import { FC } from "react";
import { createStyleSheet } from "@/utils/createStyleSheet.ts";
import { TabsMenu } from "@/components/Layout/TabsMenu.tsx";
import LayoutUser from "@/components/Layout/LayoutUser.tsx";

type props = {
  currentRoute: string;
  setRoute: (path: string) => void;
  reload: () => void;
}

const LayoutBar: FC<props> = ({ currentRoute, setRoute, reload }) => {
  return (
    <>
      <div
        className="w-screen grid grid-rows-1 grid-cols-[1fr_auto_auto] items-center shadow-sm"
        style={styles.container}
      >
        <div style={styles.title} className="select-none">
          AnomalousVehicleTrajectoryAlertSystem
        </div>
        <div className="h-full">
          <TabsMenu currentRoute={currentRoute} setRoute={setRoute} />
        </div>
        <div>
          <LayoutUser reload={reload} />
        </div>
      </div>
    </>
  );
};
export default LayoutBar;
const styles = createStyleSheet({
  container: {
    height: "var(--layout-bar-height)",
    paddingRight: "calc(var(--spacing) * 4)",
    paddingLeft: "calc(var(--spacing) * 4)",
    backgroundColor: " var(--layout-bar-bg)",
    color: "var(--layout-bar-color)"
  },
  title: {
    color: "var(--layout-bar-title-color)"
  }
});
